### ISSUE TITLE
bswap does nothing on Buffers

### ISSUE THREAD

**Issue by michael-ts** [zbjornson/node-bswap#2]
Documentation says: "For node.js 4.x and later, this also works on Buffers."

Running on node v6.6.0:

```
var bswap = require("bswap")
var x = new Buffer([1,2,3,4,5])
bswap(x)

```

Output:

```
> var bswap = require("bswap")
undefined
> var x = new Buffer([1,2,3,4,5])
undefined
> x
<Buffer 01 02 03 04 05>
> bswap(x)
undefined
> x
<Buffer 01 02 03 04 05>

```

**Comment by zbjornson** [comment]
Sorry, the docs aren't clear on that. Buffers are considered Uint8 arrays by default so nothing will happen. You need to first make a typed array view on the buffer:

```js
// Buffer b
var ui32 = new Uint32Array(b.buffer, b.byteOffset, b.byteLength / Uint32Array.BYTES_PER_ELEMENT);
```

(Substituting Uint32Array with the correct width for your data.)

**Comment by michael-ts** [comment]
@zbjornson Ah, sorry about that.  I guess I misread the documentation as well.. I'm trying to reverse the endian order at the bit level, so 0000_0001b -> 1000_0000b, etc.  Guess I'll have to look elsewhere.
