### ISSUE TITLE
how do you enable or disable AVX512?

### ISSUE THREAD

**Issue by qqwangxiaow** [zbjornson/node-bswap#4]
Hi,I want to know how to enable AVX512 for node.js if I tested it in cascadelake machine.

**Comment by zbjornson** [comment]
You need to define `BSWAP_USE_AVX512` when compiling. This should work:
```
CFLAGS=-DBSWAP_USE_AVX512 CXXFLAGS=-DBSWAP_USE_AVX512 yarn add zbjornson/node-bswap
```

and you can confirm that worked with
```js
const bswap = require("bswap");
console.log(bswap.ise); // 'AVX512'
```

I think I've only benchmarked on early Skylake and not newer Cascade Lake. Especially if you find it to be faster, I'd be interested to hear your findings.

**Comment by qqwangxiaow** [comment]
I tried on i9 9900x machine with AVX512 and Cascade Lake on Aliyun.There no big gap for AVX512 and AVX2.

**Comment by zbjornson** [comment]
Thanks for reporting back!
