### ISSUE TITLE
TypeError when using in windows

### ISSUE THREAD

**Issue by nikhil3000** [zbjornson/node-bswap#5]
I am using bswap in my react project which is packed using electron. When I create a package for mac everything works fine but my project throws an error on bswap when using the package created for windows. 

TypeError: (0, c.default) is not a function

Here is my code: 

```
currentPacketNumber = new Uint32Array([intToHexa(ele)])
      bswap(currentPacketNumber)
      return typedarrayToBuffer(currentPacketNumber).toString('hex')

const intToHexa = ele => `0x${Number(ele).toString(16)}`
```

Please help me. Tell me the more details you need.

**Comment by zbjornson** [comment]
That `TypeError` doesn't give enough info to diagnose the problem... I've never done anything with Electron so I'm not sure what to suggest, sorry.

**Comment by nikhil3000** [comment]
I couldn't fix the issue and realised I didn't actually have to use bswap here. So I directly created the typearray in the correct endian. Thanks for the reply.
